{{- if .Values.operator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tacito-square.fullname" . }}-operator
  labels:
    {{- include "tacito-square.labels" (dict "component" "operator" "context" .) | nindent 4 }}
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
      {{- include "tacito-square.selectorLabels" (dict "component" "operator" "context" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tacito-square.selectorLabels" (dict "component" "operator" "context" .) | nindent 8 }}
    spec:
      serviceAccountName: {{ include "tacito-square.fullname" . }}-operator
      containers:
        - name: operator
          image: {{ include "tacito-square.image" (dict "registry" .Values.operator.image.registry "name" .Values.operator.image.name "tag" .Values.operator.image.tag "global" .Values.global) }}
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.operator.config.port }}
              protocol: TCP
          env:
            - name: TS_OPERATOR_LOG_LEVEL
              value: {{ .Values.operator.config.logLevel | quote }}
            - name: TS_OPERATOR_AGENT_LOG_LEVEL
              value: {{ .Values.agent.config.logLevel | quote }}
            - name: TS_OPERATOR_PORT
              value: {{ .Values.operator.config.port | toString | quote }}
            - name: TS_OPERATOR_AGENT_PORT
              value: {{ .Values.agent.config.port | quote }}
            - name: TS_OPERATOR_OTEL_ENDPOINT
              value: {{ .Values.operator.config.otel.endpoint | quote }}
            - name: TS_OPERATOR_AGENT_OTEL_ENDPOINT
              value: {{ .Values.agent.config.otel.endpoint | quote }}
            - name: TS_OPERATOR_NATS_URL
              value: {{ .Values.operator.config.nats.url | quote }}
            - name: TS_OPERATOR_AGENT_NATS_URL
              value: {{ .Values.agent.config.nats.url | quote }}
            - name: TS_OPERATOR_TLS_CA_CERT_PATH
              value: {{ .Values.operator.config.tls.caCertPath | quote }}
            - name: TS_OPERATOR_AGENT_TLS_CA_CERT_PATH
              value: {{ .Values.agent.config.tls.caCertPath | quote }}
          livenessProbe:
            {{- toYaml .Values.operator.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.operator.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
          volumeMounts:
            - name: ca-cert
              mountPath: /etc/ssl/tacito
              readOnly: true
      volumes:
        - name: ca-cert
          configMap:
            name: {{ .Values.global.caTrustBundle.configMapName }}
            items:
              - key: {{ .Values.global.caTrustBundle.key }}
                path: ca.crt
{{- end }}
