{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  labels:
    {{- include "tacito-square-infra.labels" . | nindent 4 }}
data:
  tacito-realm.json: |
    {
      "realm": "tacito",
      "enabled": true,
      "sslRequired": "external",
      "clients": [
        {
          "id": "d867b740-aa9e-4e9d-b155-65daf479d6ce",
          "clientId": "tacito",
          "name": "Tacito-Square",
          "description": "A silent plaza where agents gather, deliberate, and act without noise.",
          "rootUrl": "http://localhost/ui",
          "baseUrl": "",
          "clientAuthenticatorType": "client-secret",
          "secret": "BodOiaMLOJwKIfAwbiK0xuAw6EwwKD8f",
          "redirectUris": [
            "/api/v1/auth/callback"
          ],
          "webOrigins": [
            ""
          ],
          "attributes": {
            "logout.confirmation.enabled": "true",
            "client.secret.creation.time": "1782079499",
            "standard.token.exchange.enabled": "false",
            "frontchannel.logout.session.required": "true",
            "post.logout.redirect.uris": "http://localhost/ui",
            "oauth2.device.authorization.grant.enabled": "false",
            "use.jwks.url": "false",
            "backchannel.logout.revoke.offline.tokens": "true",
            "realm_client": "false",
            "oidc.ciba.grant.enabled": "false",
            "backchannel.logout.session.required": "true",
            "backchannel.logout.url": "http://ts-tacito-square-bff:8083/ui/api/v1/auth/backchannel-logout",
            "display.on.consent.screen": "false",
            "dpop.bound.access.tokens": "false"
          }
        }
      ]
    }
{{- end }}
