{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  labels:
    {{- include "tacito-square-infra.labels" . | nindent 4 }}
data:
  tacito-realm.json: |
    {
      "realm": "tacito",
      "enabled": true,
      "sslRequired": "external",
      "clients": [
        {
          "id": "d867b740-aa9e-4e9d-b155-65daf479d6ce",
          "clientId": "tacito",
          "name": "Tacito-Square",
          "description": "A silent plaza where agents gather, deliberate, and act without noise.",
          "rootUrl": "http://localhost:8083",
          "adminUrl": "http://localhost:8083",
          "baseUrl": "",
          "clientAuthenticatorType": "client-secret",
          "secret": "BodOiaMLOJwKIfAwbiK0xuAw6EwwKD8f",
          "redirectUris": [
            "/api/bff/v1/auth/callback"
          ],
          "webOrigins": [
            "/api/bff/v1/auth/backchannel-logout"
          ]
        }
      ]
    }
{{- end }}
