global:
  caTrustBundle:
    configMapName: "ts-infra-tacito-square-infra-ca-bundle"

keeper:
  image:
    pullPolicy: Never
  config:
    db:
      url: "postgres://ts-infra-postgresql:5432/tacito"
      username: "tacito"
      password: "tacito-dev"
    otel:
      endpoint: "ts-infra-otel-collector:4317"
    nats:
      url: "nats://ts-infra-nats-headless:4222"
operator:
  image:
    pullPolicy: Never
  config:
    otel:
      endpoint: "ts-infra-otel-collector:4317"
    nats:
      url: "nats://ts-infra-nats-headless:4222"
agent:
  config:
    otel:
      endpoint: "ts-infra-otel-collector:4317"
    nats:
      url: "nats://ts-infra-nats-headless:4222"
    redis:
      url: "redis://:tacito-redis-dev@ts-infra-redis-headless:6379"
    qdrant:
      url: "ts-infra-qdrant:6334"

bff:
  enabled: false
