global:
  caTrustBundle:
    configMapName: "ts-infra-tacito-square-infra-ca-bundle"

keeper:
  image:
    pullPolicy: Never
  config:
    db:
      url: "postgres://ts-infra-postgresql:5432/tacito"
      username: "tacito"
      password: "tacito-dev"
    otel:
      endpoint: "ts-infra-otel-collector:4317"
operator:
  enabled: false
bff:
  enabled: false
