apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tacito-square.fullname" . }}-keeper-db
  labels:
    {{- include "tacito-square.labels" (dict "component" "keeper" "context" .) | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.keeper.config.db.password | quote }}
