apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tacito-square.fullname" . }}-keeper
  labels:
    {{- include "tacito-square.labels" (dict "component" "keeper" "context" .) | nindent 4 }}
