{{- if .Values.client.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tacito-agent.fullname" . }}-client
  labels:
    {{- include "tacito-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "tacito-agent.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: client
  template:
    metadata:
      labels:
        {{- include "tacito-agent.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: client
    spec:
      containers:
        - name: client
          image: "{{ if .Values.client.image.registry }}{{ .Values.client.image.registry }}/{{ end }}{{ .Values.client.image.name }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          command: ["tail", "-f", "/dev/null"]
          env:
            - name: NATS_URL
              value: {{ .Values.nats.url | quote }}
          resources:
            {{- toYaml .Values.client.resources | nindent 12 }}
{{- end }}
