#!/usr/bin/env bash
# test/helm/test_agent_standalone_chart.sh — Comprehensive dry-run validation tests for standalone agent Helm chart
# Part of TASK-M5.7.3 TDD cycle.
# Run: bash test/helm/test_agent_standalone_chart.sh

set -euo pipefail

AGENT_CHART="tools/helm/tacito-agent"
RELEASE="my-agent"

PASS=0
FAIL=0
ERRORS=()

pass() { ((PASS++)); printf "  \033[32m✓ PASS\033[0m %s\n" "$1"; }
fail() { ((FAIL++)); ERRORS+=("$1"); printf "  \033[31m✗ FAIL\033[0m %s\n" "$1"; }

section() { printf "\n\033[1m── %s ──\033[0m\n" "$1"; }

# ── 1. Chart existence check ──────────────────────────────
section "Chart Directory Check"

if [ -d "${AGENT_CHART}" ]; then
  pass "Standalone chart directory exists"
else
  fail "Standalone chart directory exists"
fi

# ── 2. Chart.yaml validation ──────────────────────────────
section "Chart Metadata Check"

if [ -f "${AGENT_CHART}/Chart.yaml" ]; then
  pass "Chart.yaml exists"
  if grep -q "name: tacito-agent" "${AGENT_CHART}/Chart.yaml"; then
    pass "Chart name is correct (tacito-agent)"
  else
    fail "Chart name is correct (tacito-agent)"
  fi
else
  fail "Chart.yaml exists"
fi

# Create a temporary file for rendered templates
TEMPLATE_FILE=$(mktemp)
trap "rm -f ${TEMPLATE_FILE}" EXIT

# ── 3. Profile: Default Values ────────────────────────────
section "Profile: Default Values"

if helm template "${RELEASE}" "${AGENT_CHART}" > "${TEMPLATE_FILE}" 2>/dev/null; then
  pass "Render with defaults succeeds"
else
  fail "Render with defaults succeeds"
fi

# Assert ConfigMap named properly
if grep -q "name: ${RELEASE}-tacito-agent-config" "${TEMPLATE_FILE}" 2>/dev/null; then
  pass "ConfigMap named '${RELEASE}-tacito-agent-config' rendered"
else
  fail "ConfigMap named '${RELEASE}-tacito-agent-config' rendered"
fi

# Assert standard env var keys
REQUIRED_KEYS=(
  "TS_AGENT_ID"
  "TS_AGENT_NAME"
  "TS_AGENT_TENANT_ID"
  "TS_AGENT_COMMUNITY_REF"
  "TS_AGENT_LLM_MODEL"
  "TS_AGENT_LLM_ENDPOINT"
  "TS_AGENT_LLM_TEMPERATURE"
  "TS_AGENT_LLM_MAX_TOKENS"
  "TS_AGENT_SYSTEM_PROMPT"
  "TS_AGENT_REDIS_URL"
  "TS_AGENT_REDIS_KEY_NAMESPACE"
  "TS_AGENT_REDIS_TTL_SECONDS"
  "TS_AGENT_QDRANT_URL"
  "TS_AGENT_QDRANT_COLLECTION_NAME"
  "TS_AGENT_QDRANT_VECTOR_DIMENSION"
  "TS_AGENT_NATS_URL"
  "TS_AGENT_S3_URL"
  "TS_AGENT_S3_BUCKET"
)

for key in "${REQUIRED_KEYS[@]}"; do
  if grep -q "${key}:" "${TEMPLATE_FILE}" 2>/dev/null; then
    pass "ConfigMap contains key: ${key}"
  else
    fail "ConfigMap contains key: ${key}"
  fi
done

# Assert Deployment
if grep -q "kind: Deployment" "${TEMPLATE_FILE}" 2>/dev/null && grep -q "name: ${RELEASE}-tacito-agent" "${TEMPLATE_FILE}" 2>/dev/null; then
  pass "Deployment my-agent-tacito-agent rendered"
else
  fail "Deployment my-agent-tacito-agent rendered"
fi

# Assert agent component labels are correct
if grep -A 10 "selector:" "${TEMPLATE_FILE}" | grep -q "app.kubernetes.io/component: agent" 2>/dev/null; then
  pass "Deployment selector includes app.kubernetes.io/component: agent"
else
  fail "Deployment selector includes app.kubernetes.io/component: agent"
fi

if grep -A 15 "template:" "${TEMPLATE_FILE}" | grep -q "app.kubernetes.io/component: agent" 2>/dev/null; then
  pass "Deployment pod template includes app.kubernetes.io/component: agent"
else
  fail "Deployment pod template includes app.kubernetes.io/component: agent"
fi

# Assert Secret is generated by default with apiKey
if grep -q "kind: Secret" "${TEMPLATE_FILE}" 2>/dev/null && grep -q "name: tacito-agent-llm-secret" "${TEMPLATE_FILE}" 2>/dev/null; then
  pass "Secret 'tacito-agent-llm-secret' is generated by default"
else
  fail "Secret 'tacito-agent-llm-secret' is generated by default"
fi

if grep -A 5 "api-key:" "${TEMPLATE_FILE}" | grep -q "dummy-key" 2>/dev/null; then
  pass "Secret contains correct default apiKey 'dummy-key'"
else
  fail "Secret contains correct default apiKey 'dummy-key'"
fi

# Assert ConfigMap binding
if grep -A 10 "containers:" "${TEMPLATE_FILE}" | grep -q "envFrom:" 2>/dev/null; then
  pass "Deployment uses envFrom"
else
  fail "Deployment uses envFrom"
fi

# Assert probes
if grep -A 5 "livenessProbe:" "${TEMPLATE_FILE}" | grep -q "path: /healthz" 2>/dev/null; then
  pass "Liveness probe matches /healthz"
else
  fail "Liveness probe matches /healthz"
fi



# ── 4. Profile: Custom Overlays ───────────────────────────
section "Profile: Custom Overrides"

CUSTOM_NAME="static-alpha"
CUSTOM_PROMPT="You are a customized standalone agent.
Deliver precise replies."
CUSTOM_TEMP="0.9"

if helm template "${RELEASE}" "${AGENT_CHART}" \
  --set agent.name="${CUSTOM_NAME}" \
  --set agent.systemPrompt="${CUSTOM_PROMPT}" \
  --set agent.llm.temperature="${CUSTOM_TEMP}" > "${TEMPLATE_FILE}" 2>/dev/null; then
  pass "Render with custom overlays succeeds"
else
  fail "Render with custom overlays succeeds"
fi

# Assert overridden values in ConfigMap
if grep -q "TS_AGENT_NAME: \"${CUSTOM_NAME}\"" "${TEMPLATE_FILE}" 2>/dev/null; then
  pass "TS_AGENT_NAME overridden to '${CUSTOM_NAME}'"
else
  fail "TS_AGENT_NAME overridden to '${CUSTOM_NAME}'"
fi

if grep -q "TS_AGENT_LLM_TEMPERATURE: \"${CUSTOM_TEMP}\"" "${TEMPLATE_FILE}" 2>/dev/null; then
  pass "TS_AGENT_LLM_TEMPERATURE overridden to '${CUSTOM_TEMP}'"
else
  fail "TS_AGENT_LLM_TEMPERATURE overridden to '${CUSTOM_TEMP}'"
fi

if grep -q "TS_AGENT_SYSTEM_PROMPT: \"You are a customized standalone agent.\\\nDeliver precise replies.\"" "${TEMPLATE_FILE}" 2>/dev/null || grep -q "TS_AGENT_SYSTEM_PROMPT: \"You are a customized standalone agent.\\\nDeliver precise replies.\\\n\"" "${TEMPLATE_FILE}" 2>/dev/null || grep -q "TS_AGENT_SYSTEM_PROMPT: \"You are a customized standalone agent.\\nDeliver precise replies.\"" "${TEMPLATE_FILE}" 2>/dev/null; then
  pass "TS_AGENT_SYSTEM_PROMPT multi-line is correctly serialized with newlines"
else
  fail "TS_AGENT_SYSTEM_PROMPT multi-line is correctly serialized with newlines"
fi


# ── 5. Profile: Custom LLM Credentials Secret ────────────
section "Profile: Custom LLM Credentials Secret"

CUSTOM_SECRET="custom-key-secret"

if helm template "${RELEASE}" "${AGENT_CHART}" \
  --set agent.llm.credentialsSecret="${CUSTOM_SECRET}" \
  --set agent.llm.apiKey="" > "${TEMPLATE_FILE}" 2>/dev/null; then
  pass "Render with custom credentials secret succeeds"
else
  fail "Render with custom credentials secret succeeds"
fi

# Assert credentials secret is correctly injected
if grep -A 5 "name: TS_AGENT_LLM_API_KEY" "${TEMPLATE_FILE}" | grep -qE "name: \"?${CUSTOM_SECRET}\"?" 2>/dev/null; then
  pass "TS_AGENT_LLM_API_KEY references correct secret name '${CUSTOM_SECRET}'"
else
  fail "TS_AGENT_LLM_API_KEY references correct secret name '${CUSTOM_SECRET}'"
fi

# Assert secret custom-key-secret is NOT generated when apiKey is empty
if grep -q "name: ${CUSTOM_SECRET}" "${TEMPLATE_FILE}" 2>/dev/null; then
  fail "Secret '${CUSTOM_SECRET}' should not be generated when apiKey is empty"
else
  pass "Secret '${CUSTOM_SECRET}' is not generated when apiKey is empty"
fi


# ── 6. Profile: Dynamic Secret Generation ──────────────────
section "Profile: Dynamic Secret Generation"

if helm template "${RELEASE}" "${AGENT_CHART}" \
  --set agent.llm.apiKey="dynamic-test-key" \
  --set agent.llm.credentialsSecret="" > "${TEMPLATE_FILE}" 2>/dev/null; then
  pass "Render with dynamic secret generation succeeds"
else
  fail "Render with dynamic secret generation succeeds"
fi

# Assert generated secret has fullname-llm structure
GENERATED_SECRET_NAME="${RELEASE}-tacito-agent-llm"
if grep -q "kind: Secret" "${TEMPLATE_FILE}" 2>/dev/null && grep -q "name: ${GENERATED_SECRET_NAME}" "${TEMPLATE_FILE}" 2>/dev/null; then
  pass "Generated secret is named '${GENERATED_SECRET_NAME}'"
else
  fail "Generated secret is named '${GENERATED_SECRET_NAME}'"
fi

# Assert deployment references the generated secret
if grep -A 5 "name: TS_AGENT_LLM_API_KEY" "${TEMPLATE_FILE}" | grep -qE "name: \"?${GENERATED_SECRET_NAME}\"?" 2>/dev/null; then
  pass "TS_AGENT_LLM_API_KEY references generated secret name '${GENERATED_SECRET_NAME}'"
else
  fail "TS_AGENT_LLM_API_KEY references generated secret name '${GENERATED_SECRET_NAME}'"
fi


# ── Summary ─────────────────────────────────────────────
section "Summary"
TOTAL=$((PASS + FAIL))
printf "\n  %d/%d checks passed\n" "${PASS}" "${TOTAL}"

if [ "${FAIL}" -gt 0 ]; then
  printf "\n  \033[31mFailed checks:\033[0m\n"
  for err in "${ERRORS[@]}"; do
    printf "    - %s\n" "${err}"
  done
  printf "\n"
  exit 1
fi

printf "  \033[32mAll checks passed successfully!\033[0m\n\n"
exit 0
