# Build stage
FROM golang:1.26-alpine AS builder
WORKDIR /src
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -mod=vendor -ldflags="-s -w" -o /bin/bff ./cmd/bff

# Runtime stage
FROM gcr.io/distroless/base-nossl-debian13:nonroot
COPY --from=builder /bin/bff /bff
USER nonroot:nonroot
ENTRYPOINT ["/bff"]
